# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-28 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('date_views', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dateline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=500)),
                ('city_slug', models.SlugField(max_length=500)),
                ('state_slug', models.SlugField(max_length=500)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='dateline',
            unique_together=set([('city_slug', 'state_slug')]),
        ),
        migrations.AddField(
            model_name='article',
            name='dateline',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='date_views.Dateline'),
            preserve_default=False,
        ),
    ]
