# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-28 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('date_views', '0002_auto_20170828_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='dateline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='date_views.Dateline'),
        ),
    ]
